### ISSUE TITLE
Async/Await 强于 Promise的六个原因

### ISSUE THREAD

**Issue by peterlxb** [peterlxb/Frontend-react#177]
### [原文地址: 6 Reasons Why JavaScript’s Async/Await Blows Promises Away ](https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9)

**Comment by peterlxb** [comment]
Node现在从7.6版开始就支持async/await语法。如果你还没有尝试过，这篇文章会阐述一些原因和示例来说明你为什么应该立即使用它，并且永远不要使用旧的方式。

### Async/await 101
对于那些完全没有听说过这个主题的人:下面使一些快速预览

- **Async/await 是一种编写异步代码的新方法。之前编写异步代码的方式是使用回调(callback)和promises**。
- **Async/await 实际上是在promises的基础之上建立的。它不能与普通函数回调或NodeJs回调一起使用**。
- **Async/await 和promise一样是非阻塞的**。
- **Async/await 使编写的异步代码就像同步代码一样。这就是它的核心所在**。

### 基本语法
假设有一个函数 **getJSON** 返回一个promise，这个promise用某个JSON对象解析。我们只想调用它并记录这个JSON对象，然后返回“done”。

下面是如何使用promise来实现它:
```
const makeRequest = () =>
  getJSON()
    .then(data => {
      console.log(data)
      return "done"
    })

makeRequest()
```

下面是 async/await 实现的版本
```
const makeRequest = async () => {
  console.log(await getJSON())
  return "done"
}

makeRequest()
```

下面说明这两种方式的不同点:
1. 我们的函数前面有关键字 **async**。**await** 关键字只能在使用 **async** 定义的函数中使用。任何**async** 函数都隐式地返回一个promise, promise的解析值将是你从该函数返回的值(在我们的示例中是字符串“done”)。

2. 上面这一点意味着我们不能在代码的顶层使用await，因为它不在 **async** 函数中。 

```
// 下面这段在顶层不会有效
// await makeRequest()

// 下面这个有效
makeRequest().then((result) => {
  // do something
})
```

3. await getJSON()意味着console.log调用将等待getJSON() promise解析并打印它的值。

**Comment by peterlxb** [comment]
## 这种方式的优点

### 1.简洁干净
通过上面的例子可以看到我们缩减了很多代码。即使在上面这个人为设计的示例中，我们也节省了相当数量的代码。我们不需要书写 **.then**，创建一个匿名函数来处理响应，或者为不需要使用的变量提供 **data** 名称。我们还避免了代码嵌套。这些小优点加起来，在下面的代码示例中会体现地更加明显。

### 2.错误处理(很有用)
Async/await 使得使用相同的结构 (经典的**try/catch**) 处理同步和异步错误成为可能。在下面的promises示例中，如果 **JSON.parse** 失败，**try/catch** 无法捕获到这个错误，因为它发生在promise内部。我们需要在promises上调用 **.catch** 并复制错误处理代码，这将比你的生产模式的代码中的 **console.log** 更加复杂。

```
const makeRequest = () => {
  try {
    getJSON()
      .then(result => {
        // 这个解析可能会失败
        const data = JSON.parse(result)
        console.log(data)
      })
      // 取消这个块的注释来处理异步错误
      // .catch((err) => {
      //   console.log(err)
      // })
  } catch (err) {
    console.log(err)
  }
}
```

现在用async/await来重写上面的代码。catch就能捕获到解析过程中的错误。

```
const makeRequest = async () => {
  try {
    // 这个解析可能会失败
    const data = JSON.parse(await getJSON())
    console.log(data)
  } catch (err) {
    console.log(err)
  }
}
```

**Comment by peterlxb** [comment]
### 3. 条件句
考虑下面的代码，它获取一些数据，并根据数据中的某个值决定是返回数据还是获取更多值。

```
const makeRequest = () => {
  return getJSON()
    .then(data => {
      if (data.needsAnotherRequest) {
        return makeAnotherRequest(data)
          .then(moreData => {
            console.log(moreData)
            return moreData
          })
      } else {
        console.log(data)
        return data
      }
    })
}
```

只是看这个就让你头疼。很容易在所有嵌套(6个级别)、大括号和返回语句中迷失，这些语句只需要将最终结果返回到主promise。

当使用async/await 重写时，这个例子变得更易于阅读。

```
const makeRequest = async () => {
  const data = await getJSON()
  if (data.needsAnotherRequest) {
    const moreData = await makeAnotherRequest(data);
    console.log(moreData)
    return moreData
  } else {
    console.log(data)
    return data    
  }
}
```

**Comment by peterlxb** [comment]
### 4.中间值
你可能会遇到这样一种情况:调用promise1，然后使用它返回的结果调用promise2，然后使用两个promise的结果调用promise3。你的代码很可能是这样的: 

```
const makeRequest = () => {
  return promise1()
    .then(value1 => {
      // do something
      return promise2(value1)
        .then(value2 => {
          // do something          
          return promise3(value1, value2)
        })
    })
}
```

如果 **promise3** 不需要 **value1** ，那么很容易将promise嵌套平展一点。如果你是那种不能忍受这种情况的人，你可以把1和2的值都包含在一个**Promise.all** 中来避免更深层次的嵌套，就像这样

```
const makeRequest = () => {
  return promise1()
    .then(value1 => {
      // do something
      return Promise.all([value1, promise2(value1)])
    })
    .then(([value1, value2]) => {
      // do something          
      return promise3(value1, value2)
    })
}
```

这种方法为了可读性而牺牲了语义。**value1** 和 **value2** 没有理由同时属于一个数组，除非是为了避免嵌套promise。

使用async/await，同样的逻辑变得非常简单和直观。它会让你怀疑，在你努力让promise看起来不那么可怕的时间里，你本可以做的所有事情。

```
const makeRequest = async () => {
  const value1 = await promise1()
  const value2 = await promise2(value1)
  return promise3(value1, value2)
}
```

**Comment by peterlxb** [comment]
### 5.错误堆栈
想象一下，一段代码链式调用多个promise，然后在这条链的某个地方抛出一个错误。

```
const makeRequest = () => {
  return callAPromise()
    .then(() => callAPromise())
    .then(() => callAPromise())
    .then(() => callAPromise())
    .then(() => callAPromise())
    .then(() => {
      throw new Error("oops");
    })
}

makeRequest()
  .catch(err => {
    console.log(err);
    // 输出误导的错误信息
    // Error: oops at callAPromise.then.then.then.then.then (index.js:8:13)
  })
```

从promise链返回的错误堆栈不提供错误发生在哪里的线索。更糟的是，还有可能误导;它所包含的唯一函数名是 **callAPromise**，这个函数完全没有这个错误(文件和行号仍然很有用)。

但是，async/await 的错误堆栈指向包含错误的函数

```
const makeRequest = async () => {
  await callAPromise()
  await callAPromise()
  await callAPromise()
  await callAPromise()
  await callAPromise()
  throw new Error("oops");
}

makeRequest()
  .catch(err => {
    console.log(err);
    // 输出正确错误信息
    // Error: oops at makeRequest (index.js:7:9)
  })
```

**Comment by peterlxb** [comment]
### 6. 调试
最后很重要的是，使用 async/await 时的一个致命优势是它更容易调试。调试promise总是非常痛苦，原因有二: 

1. 不能在返回表达式(无正文)的箭头函数中设置断点。
 
![2019-02-28 11 27 52](https://user-images.githubusercontent.com/8121883/53539290-ec9fea80-3b4b-11e9-85dc-539cbae087e3.png)

2.如果你在一个 **.then** 块中设置一个断点，并使用调试快捷方式，如“step-over”，调试器将不会移动到下面的then中,它只能在同步代码中"step"。

使用async/ wait，你就不需要那么多的箭头函数，并且可以像普通同步调用一样一步一步地执行await调用。

![2019-02-28 11 27 52](https://user-images.githubusercontent.com/8121883/53539410-73ed5e00-3b4c-11e9-8af9-92774c47b3f4.png)

**Comment by peterlxb** [comment]
### 结尾
Async/await 是过去几年JavaScript中添加的最具革命性的特性之一。它使你认识到promise的语法是多么混乱，并提供了很直观的替代。
